export enum EventsActionTypes {
  GET_EVENTS_PENDING = 'GET_EVENTS_PENDING',
  GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS',
  GET_EVENTS_FAILURE = 'GET_EVENTS_FAILURE',
  ADD_EVENT_PENDING = 'ADD_EVENT_PENDING',
  ADD_EVENT_SUCCESS = 'ADD_EVENT_SUCCESS',
  ADD_EVENT_FAILURE = 'ADD_EVENT_FAILURE',
  DELETE_EVENT_PENDING = 'DELETE_EVENT_PENDING',
  DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS',
  DELETE_EVENT_FAILURE = 'DELETE_EVENT_FAILURE',
}
